### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by venugopalkatukam** [asquarezone/DevOpsClassRoom#1]
I got this message while bootstrapping

Authentication failed for user ec2-user@18.221.152.228@18.221.152.228 (Net::SSH::AuthenticationFailed)
ERROR: Net::SSH::AuthenticationFailed: Authentication failed for user ec2-user@18.221.152.228@18.221.152.228

**Comment by gogulampativishnu** [comment]
1. copy .pem file to the location where you are running the command
2. make sure SSH port is open

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
