### ISSUE TITLE
i got an error

### ISSUE THREAD

**Issue by sainath2929** [asquarezone/DevOpsClassRoom#12]
ansible@ip-172-31-91-175:~/playbooks$ ansible-playbook lamp_beginer.yml
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/ansible/playbooks/lamp_beginer.yml': line 6, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   - name: update ubuntu packages and install apache2
      apt:
         ^ here

**Comment by VENKATAREDDYVENNA** [comment]
Hi 
please show the .yml file once.

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
