### ISSUE TITLE
I am Unable to BootStrap the node getting SSH Failed Error

### ISSUE THREAD

**Issue by kasirepk2** [asquarezone/DevOpsClassRoom#13]
![image](https://user-images.githubusercontent.com/52392941/62263752-fd29f900-b43a-11e9-968f-dee6e71c07cf.png)

**Comment by kasirepk2** [comment]
![image](https://user-images.githubusercontent.com/52392941/62263832-2ba7d400-b43b-11e9-820e-bf4ac4e92cf5.png)

**Comment by NareshAnumula** [comment]
Give the path of Pem file.Even though if u could't resolve use -U instead of -x.
example:
knife bootstrap "13.127.118.152"  --sudo -i C:\Users\naresh\Downloads\chefnodes.pem -U 'ubuntu' -N "ip-172-30-2-194.ap-south-1.compute.internal"

**Comment by sharanreddy567** [comment]
you have done the bootstrap on the ./windows/system32, so change the to the pem file where it is located 
try doing bootstrap on the path where the chefnodes.pem file is located 
![Capture1](https://user-images.githubusercontent.com/53834019/62594127-feee3380-b8f6-11e9-9061-258f8940abfa.PNG)

**Comment by ghost** [comment]
please do bootstrap inside chef-repo

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
