### ISSUE TITLE
unable to bootstrap

### ISSUE THREAD

**Issue by qt-yatin527** [asquarezone/DevOpsClassRoom#14]
Hello i'm unable to boot strap node from workstation. Below is the error.
![image](https://user-images.githubusercontent.com/53309584/62354029-8fa8c600-b529-11e9-9f40-dd35ff41db76.png)

Help me to resolve the issue

**Comment by qt-yatin527** [comment]
I tried upgrading ruby in machine still facing issue

![image](https://user-images.githubusercontent.com/53309584/62359904-63934200-b535-11e9-915b-e9634109f66b.png)
Please help me in resolving this case.

**Comment by qt-yatin527** [comment]
Hello,
This is issue is self resolved by reading docs
Resolved steps:
Accepted licenses by running command chef env

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
