### ISSUE TITLE
"I got an error while i am trying to run a playbook(install lamp-stack on ubuntu )

### ISSUE THREAD

**Issue by sanjeevaduri** [asquarezone/DevOpsClassRoom#15]
![ansible error](https://user-images.githubusercontent.com/52369863/63414057-ac456900-c418-11e9-8cf1-caec53a148ba.PNG)

**Comment by shaikkhajaibrahim** [comment]
https://github.com/qt-devops/DevOpsIssues

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
