### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by sainath2929** [asquarezone/DevOpsClassRoom#16]
description:when i want to push master branch it shows error but it does not occur in other branch.
error:
$ git push -u jenorigin master
To https://github.com/sainath2929/jenkins_practice.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/sainath2929/jenkins_practice.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by shaikkhajaibrahim** [comment]
Please do git pull before push
________________________________

**Comment by sainath2929** [comment]
$ git pull https://github.com/sainath2929/jenkins_practice.git
From https://github.com/sainath2929/jenkins_practice
 * branch            HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories

**Comment by NareshAbbanapuri** [comment]
please remove github credential from your windows credential and redo things

**Comment by ghost** [comment]
please remove GitHub credentials from your windows credentials manager

**Comment by shaikkhajaibrahim** [comment]
https://www.educative.io/edpresso/the-fatal-refusing-to-merge-unrelated-histories-git-error
