### ISSUE TITLE
The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

### ISSUE THREAD

**Issue by BDprasad95** [asquarezone/DevOpsClassRoom#17]
![Screenshot (10)](https://user-images.githubusercontent.com/40328121/64471070-14f74a00-d16a-11e9-9548-8d862a411cd1.png)

**Comment by shaikkhajaibrahim** [comment]
Can you please use the machine in the cloud and reproduce this issue. I don't want you to run tomcat on your laptop

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
