### ISSUE TITLE
unable to install tree in node, in Ansible

### ISSUE THREAD

**Issue by saibalaji1** [asquarezone/DevOpsClassRoom#18]
ansible@ip-172-31-16-123:~$ ansible-playbook -i inventory tree.yml

PLAY [all] **************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************
fatal: [172.31.21.138]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.31.21.138 closed.\r\n", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "rc": 1}
ok: [localhost]

TASK [install tree] *****************************************************************************************************
ok: [localhost]
        to retry, use: --limit @/home/ansible/tree.retry

PLAY RECAP **************************************************************************************************************
172.31.21.138              : ok=0    changed=0    unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=0

**Comment by shaikkhajaibrahim** [comment]
share your inventory and one more thing did you configure visudo for this user to be password less. If you want to enter password you need to change the command of ansible-playbook to pass the password of this user.

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
