### ISSUE TITLE
unable to get update to the Powers hell to knife node link 

### ISSUE THREAD

**Issue by SyedRaz** [asquarezone/DevOpsClassRoom#2]
![Capture](https://user-images.githubusercontent.com/48674220/55169798-65ba4e00-519b-11e9-9c1a-adf6c7f448e2.PNG)

**Comment by gogulampativishnu** [comment]
did you copied the .PEM file to the folder from where you are running the command?

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
