### ISSUE TITLE
Bootstrap connection making issue, ssh authentication 

### ISSUE THREAD

**Issue by SyedRaz** [asquarezone/DevOpsClassRoom#3]
![image](https://user-images.githubusercontent.com/48674220/55229389-dcf6ed00-5242-11e9-9393-8a28f1f573b8.png)

The above snapshot is with user name ""

Below you can find without ""
![image](https://user-images.githubusercontent.com/48674220/55229550-5db5e900-5243-11e9-96f8-48737b8da10d.png)

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
