### ISSUE TITLE
Ansible Issue while writing loop 

### ISSUE THREAD

**Issue by Sanad09** [asquarezone/DevOpsClassRoom#4]
Hello,

As I was practicing creating a loop playbook to install multiple RHEL packages I encountered the below where it installed 2 out of the three packages only (linuxptp and logwatch) as I misspelled one of the packages name (mtools).

 My question is, why do I only see a failed count (failed=1) with no changed count (change=0) in the "Play Recap". Even though the task didn't fully fail as it actually installed the two packages that I spelled their names correctly and I can even verify that when logging into the agent and running # rpm -qa | grep Package_Name.

Can you pleas explain to me?

See below as the output of the ansible Play and the playbook itself:

ansible@ip-172-31-37-237:~/playbooks$ ansible-playbook -i inventory loop.yml 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [18.216.212.96]
ok: [18.216.129.31]
ok: [localhost]

TASK [Install package] *********************************************************
skipping: [18.216.129.31] => (item=mtool) 
skipping: [18.216.129.31] => (item=linuxptp) 
skipping: [18.216.129.31] => (item=logwatch) 
skipping: [localhost] => (item=mtool) 
skipping: [localhost] => (item=linuxptp) 
skipping: [localhost] => (item=logwatch) 
failed: [18.216.212.96] (item=mtool) => {"changed": false, "item": "mtool", "msg": "No package matching 'mtool' found available, installed or updated", "rc": 126, "results": ["No package matching 'mtool' found available, installed or updated"]}
changed: [18.216.212.96] => (item=linuxptp)
changed: [18.216.212.96] => (item=logwatch)
	to retry, use: --limit @/home/ansible/playbooks/loop.retry

PLAY RECAP *********************************************************************
18.216.129.31              : ok=1    changed=0    unreachable=0    failed=0   
18.216.212.96              : ok=1    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ansible@ip-172-31-37-237:~/playbooks$ cat loop.yml 
- hosts: all
  become: yes
  tasks:
   - name: Install package
     package:
       name: "{{ item }}"
       state: present
     loop:
       - mtool
       - linuxptp
       - logwatch
     when: ansible_os_family != "Debian"    
ansible@ip-172-31-37-237:~/playbooks$

Here you can see the two package did get installed on the Node:
root@ip-172-31-34-165 ~]# rpm -qa | grep -i logwatch
logwatch-7.4.0-35.20130522svn140.el7_5.noarch
[root@ip-172-31-34-165 ~]# rpm -qa | grep -i linuxptp
linuxptp-1.8-6.el7.x86_64
[root@ip-172-31-34-165 ~]#

Regards,

**Comment by Sanad09** [comment]
Hello,

Does anyone have any thoughts on this please?

Regards,

**Comment by bhaskardegala** [comment]
please raise your issue in following link [click here](https://github.com/QT-DevOps/DevOpsIssues/issues)
this is not the right place to raise your issues 
thanks

**Comment by dharmatejadevops** [comment]
hi sanad09, 
may be the bellow link will helps you.
https://docs.ansible.com/ansible/2.4/playbooks_loops.html

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
