### ISSUE TITLE
terraform validating the issue

### ISSUE THREAD

**Issue by saipranay54** [asquarezone/DevOpsClassRoom#8]
![terraform issue](https://user-images.githubusercontent.com/50736120/57917726-e69be900-78b2-11e9-96bb-a73382ae876d.png)

hi guys,
I am getting the issue while validate the below code 
Error: aws_vpc.ntiernetwork: resource repeated multiple times
           aws_vpc.ntiernetwork: resource repeated multiple times
please help me out
i have created the three files and written a code as below and i executed the code
code 1:resource "aws_vpc" "ntiernetwork" {
 cidr_block="10.10.0.0/16"

    type{
        Name="ntier"
    }
}

resource "aws_subnet" "web" {
    vpc_id="${aws_vpc.ntiernetwork.id}"
    cidr_block="10.10.0.0/24"

tags{
    Name="web"
}

}

  

resource "aws_subnet" "business" {
     vpc_id="${aws_vpc.ntiernetwork.id}"
     cidr_block="10.10.0.0/24"

tags{
    Name="business"
}
}
resource "aws_subnet" "db" {
      vpc_id="${aws_vpc.ntiernetwork.id}"
    cidr_block="10.10.0.0/24"

tags{
    Name="db"
}
}
code2:resource "aws_vpc" "ntiernetwork" {
 cidr_block="10.10.0.0/16"

    type{
        Name="ntier"
    }
}

resource "aws_subnet" "web" {
    vpc_id="${aws_vpc.ntiernetwork.id}"
    cidr_block="10.10.0.0/24"

tags{
    Name="web"
}

}

  

resource "aws_subnet" "business" {
     vpc_id="${aws_vpc.ntiernetwork.id}"
     cidr_block="10.10.0.0/24"

tags{
    Name="business"
}
}
resource "aws_subnet" "db" {
      vpc_id="${aws_vpc.ntiernetwork.id}"
    cidr_block="10.10.0.0/24"

tags{
    Name="db"
}
}
code3:resource "aws_instance" "web_instance" {
     ami= "ami-0a313d6098716f372"
     instance_type="t2.micro"
     key_name="vpclearn"
     subnet_id="${aws_subnet.web.id}"

     tags{
         Name="web"
     }
}

resource "aws_instance" "db_instance" {
     ami=" ami-0a313d6098716f372"
     instance_type="t2.micro"
     key_name="vpclearn"
     subnet_id="${aws_subnet.web.id}"

     tags{
         Name="db"
     }
}

resource "aws_instance" "business_instance" {
     ami=" ami-0a313d6098716f372"
     instance_type="t2.micro"
     key_name="vpclearn"
     subnet_id="${aws_subnet.web.id}"

     tags{
         Name="business"
     }
}
please help me to resolve the same

**Comment by ghost** [comment]
sai pranay i think your issue resolved in devops issues

**Comment by saipranay54** [comment]
Yeah even I closed the issue

**Comment by ghost** [comment]
please close this one also

**Comment by saipranay54** [comment]
Sure I'll close tomorrow naresh

**Comment by shaikkhajaibrahim** [comment]
Please raise issues @ https://github.com/qt-devops/DevOpsIssues
